### PR TITLE
Add Australia/New Zealand channels and build target

### PR DESCRIPTION
**Pull request by r51n**
Since none of the existing channel plans was safe to use in AU/NZ, I made this channel plan that should make best use of the 915-928MHz range while avoiding known busy frequencies like RFID, LoRaWAN etc.

### CODE REVIEW

**Comment by geeksville** [comment]
Hmm - from a previous discussion with someone in NZ, it seemed like 915MHz and up was good?  See this thread:

https://github.com/meshtastic/Meshtastic-device/issues/317#issuecomment-689021445

What do you think?

**Comment by r51n** [comment]
Ooh, I didn't notice that thread. I think the comments in the thread are *not incorrect*, but the current code doesn't reflect that. 

https://github.com/meshtastic/Meshtastic-device/blob/004f1f625ba91d9b0f9fa5d2dd390aa80f9ed231/src/mesh/MeshRadio.h#L9-L12

The US channel plan defines 13 channels from **903.08MHz** with a 2.16MHz spacing. This means US channels 0-5 fall outside the **915**-928MHz AU/NZ range and are **not safe to use**. 

It makes sense to have a separate channel plan.

**Comment by geeksville** [comment]
oh great point!  I'll happily merge this change.

**Comment by r51n** [comment]
Sorry, I don't think that worked. Did I mess up anything at my end?

**Pull request merged**
