### PR TITLE
wire in OEM.proto keystore

### PR DESCRIPTION
**Pull request by caveman99**

### CODE REVIEW

**Comment by caveman99** [comment]
generate the file with https://flasher.meshtastic.org/oem.php and put it in /data/oem/ before creating littlefs

**Comment by sachaw** [comment]
Very nice! I'll get around to adding this to the API/site at some point pending se changed in the js lib.
Do you have the PHO code available?

**Comment by caveman99** [comment]
@sachaw https://github.com/caveman99/Meshtastic-webflash

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/custom-boot-screen-protobuf-api/6940/3

**Pull request merged**
