### PR TITLE
Add support for SH1106 controller

### PR DESCRIPTION
**Pull request by mrvdb**
The SH1106 is almost indistinguisable from a SSD1306.

- the nr of columns in the sh1106 is 132 vs 128
- use the proper includes/library functions when in use

This needs https://github.com/meshtastic/esp8266-oled-ssd1306/pull/1

Related to issue #178

### CODE REVIEW

**Comment by mrvdb** [comment]
- I haven't seen a difference yet with the 132 vs 128 columns (largely I think because I haven't seen all the pages when actually using a channel)
- it might be possible to use the display width to auto-detect the controller perhaps?

**Comment by geeksville** [comment]
> it might be possible to use the display width to auto-detect the controller perhaps?
Possibly.  I really don't know because I haven't read the datasheets for either of these two chips.  But I bet it would be possible to find some particular i2c register that is different between them and use that to "probe" to figure out which chip is stuffed.  After doing that probe the correct class could be instantated. 

I think that would be a great separate pull request if you wanted to add it.  But your current approach looks fine to me.

**Comment by mrvdb** [comment]
Thanks for merging this!. To make it complete, the lib PR needs to be merged as well, not sure if you missed that. (PR is here: https://github.com/meshtastic/esp8266-oled-ssd1306/pull/1 )

**Comment by geeksville** [comment]
@mrvdb ooh I did!  thanks for reminding me

**Pull request merged**
