### PR TITLE
Add stubs so that portduino can build with wifi. cc @mc-hamster

### PR DESCRIPTION
**Pull request by geeksville**
Stuff

### CODE REVIEW

**Comment by geeksville** [comment]
oops the CI build failed for nrf25, I'll fix today - cc @mc-hamster .

**Comment by geeksville** [comment]
btw @mc-hamster what do you think about merging this branch now with dev?  seems to have some good user visible features now.

**Comment by mc-hamster** [comment]
Let me make one change to the the HTML Interface to indicate that it is a WIP and I have David's latest changes in my branch to merge in. I don't want people filing bugs on the webui.

**Comment by mc-hamster** [comment]
Alright, go ahead and merge it.

**Pull request merged**
