### PR TITLE
Automatic screen carousel behavior implementation (auto_screen_carousel_secs user preference)

### PR DESCRIPTION
**Pull request by thebentern**
This is the simplest MVP version possible. I've done some initial testing and it seems to behave well overall. It also respects static frames like the bluetooth pin from what I can tell.
@mc-hamster, picking up from our discussion in the discord, I was way over-complicating things... After digging a bit more, it turns out we can accomplish everything within Screen.cpp with just a few strategically placed lines of code.

### CODE REVIEW

**Comment by crossan007** [comment]
Nice!!

If you want some more inspiration; I have a semi-abandoned branch that makes the dots "bounce" when there are message notifications, and makes double-pressing the button open either the currently notifying frame, or go to the first frame if there are no notifications: https://github.com/meshtastic/Meshtastic-device/compare/master...crossan007:adjust_frame_notifications?expand=1

**Comment by thebentern** [comment]
> Nice!!
> 
> If you want some more inspiration; I have a semi-abandoned branch that makes the dots "bounce" when there are message notifications, and makes double-pressing the button open either the currently notifying frame, or go to the first frame if there are no notifications: https://github.com/meshtastic/Meshtastic-device/compare/master...crossan007:adjust_frame_notifications?expand=1

Thanks, Charles! This is a huge help. I've been getting exited about slowly updating some of the OLED screen behavior. I think that the interface does need to shift more towards an "opt-in" to notifications for better usability. It's tricky to try to implement a good usable UI on a tiny screen with a single user button.

**Comment by mc-hamster** [comment]
Thanks!

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/meshtastic-device-1-2-48-alpha/4359/1

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/meshtastic-device-1-2-49-5354c49-alpha/4502/1

**Pull request merged**
