### PR TITLE
WIP: unify the RAK targets into one firmware

### PR DESCRIPTION
**Pull request by caveman99**
First steps to unify GPS Lib for RAK1910 and RAK12500

### CODE REVIEW

**Comment by caveman99** [comment]
I changed the names back so the CI will build stuff. the 4631_5005 will be the new combined firmware for now. Please test this build on both 5005 and 19003 baseboards with both GPS modules - lock is not expected, but debug log should show them working in UBX mode, the 12500 GPS on I2C Bus.

**Comment by sachaw** [comment]
Great work, One change I think we should investigate before this gets merged is getting NanoPB to not put it's version info into the files it generates, https://github.com/meshtastic/Meshtastic-device/blob/eae9673ddb6bba248e0de373bf348404ce520821/src/mesh/generated/apponly.pb.h#L2 for example.

Otherwise every time we update (like this pr) we will change every generated file (needless changes)

**Comment by caveman99** [comment]
- The build errors for the RAK targets are because it tries to build the old ones. there's only rak4631 and rak4631_eink now.
- The build errors for ESP32 i have no idea on. I don't think i changed anything that would cause that. Investigating.

**Review by thebentern — COMMENTED** [review]
Looks good to me. Do you want to wait to integrate until the crypto changes are complete or go ahead and move forward with what you have now and tackle the crypto in another effort?

**Comment by sachaw** [comment]
I'm going to merge this before it gets too far behind, crypto can be a separate PR

**Pull request merged**
