### PR TITLE
fix #272 add support for tlora-v2-1-1.6

### LINKED ISSUE #272: Brightness slider activates on TTGO-LoRa32-V2.1 with serial Puttty connection.
Anytime TTGO-LoRa32-V2.1 is connected with a serial connection with Putty or the Python API, the brightness slider activates and repeatedly  cycles from low to high. Attempting to edit the screen by pulling the GPIO0 low to ground does nothing. Ending the Putty or Python session returns the unit to normal operation.

This may not be an appropriate issue, as TTGO-LoRa32-V2 is listed as supported, but no mention of V2.1. If so, sorry , Please ignore and close.

### PR DESCRIPTION
**Pull request by aHVzY2g**
adds support for tlora-v2-1-1.6 and changes names from ttgo-lora32-... to tlora-...

(clean version of #274)

### CODE REVIEW

**Comment by slavino** [comment]
Is this the board you named "tlora-v2-1-1.6" ?

**Comment by aHVzY2g** [comment]
I don't have it my self, but it looks like it is. In PR #274 is more refrence

**Comment by slavino** [comment]
Then with TTGO boards I would suggest to use the labels from the boards itself or keep an up to date "Hashmap" with all the references :)

"TTGO T3_V1.6 20180606" - is in meshtastic from today on referenced as "tlora-v2-1-1.6" :)

**Comment by aHVzY2g** [comment]
the "Hashmap" is probably the way to go. @slavino out of interest, as what was it advertised as you bought it?

**Pull request merged**
