### PR TITLE
Add mqtt_username and mqtt_password user preferences

### PR DESCRIPTION
**Pull request by joshpirihi**
Added mqtt username and password to the UserPreferences (I have a corresponding pull request for the protobufs [here](https://github.com/meshtastic/Meshtastic-protobufs/pull/61) )

If the default server is used, it will default to the hardcoded credentials, but not for a custom mqtt server.

### CODE REVIEW

**Comment by joshpirihi** [comment]
Issue #1002

**Comment by thebentern** [comment]
Great work! This will be huge for bridging into other networks

**Comment by mc-hamster** [comment]
Thanks!

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/meshtastic-firmware-1-2-50-41dcfdd-alpha/4612/1

**Pull request merged**
