### PR TITLE
Fix #207 adjust OLED Brightness by attachDuringLongPress

### LINKED ISSUE #207: Make oled brightness adjustable
via a new field in the UserPreferences protobuf and fixing the OLED library to give us a brightness API.  See the SSD1306 datasheet for instructions.

### PR DESCRIPTION
**Pull request by aHVzY2g**
adjust the OLED Brightness by "attachDuringLongPress" from "OneButton". It will start by 150 and cycle trough 0 to 254 as long as the button is pressed.

And sry for all the commits 😬, I just can't figure out how to revert a commit without making another commit 😅.

### CODE REVIEW

**Comment by aHVzY2g** [comment]
I just added a brightness bar so it is simpler for the user to adjust the brightness.

pic

**Comment by geeksville** [comment]
@aHVzY2g Thanks sounds really great! btw - just for git knowledge purposes, you'll love "git rebase -i HEAD~6" it will let you interactively merge/edit the last 6 commits.  Do you want to give it a try?

You'll want to change the first word on all but the first line to "s" (for squash).

then you can do "git push -f" and this PR will then be perfect.

(If not no worries - I can try doing it later, but much easier for me if you do it)

**Comment by geeksville** [comment]
yay!  thanks so much for squashmofing!

**Comment by aHVzY2g** [comment]
> 
> 
> yay! thanks so much for squashmofing!

thank you, that was way easier than I expected

**Pull request merged**
