### PR TITLE
[OLED] Cyrillic support & localization guide

### PR DESCRIPTION
**Pull request by osmanovv**
* Cyrillic font for OLED
* OLED localization guide

### CODE REVIEW

**Comment by caveman99** [comment]
I like this change, cause it has a low memory footprint if you don't define OLED_RU. Any chance we can get this for 1.3 as well? Would work fine with the new compression lib.

**Comment by caveman99** [comment]
@osmanovv would you consider rebasing this PR to 1.3? 1.2 will only receive bugfixes, no new features.

**Comment by osmanovv** [comment]
@caveman99, so yes. I did not test it on v1.3, could it be cherry-picked to that branch?

**Comment by garthvh** [comment]
> could it be cherry-picked to that branch?

Using the edit link on the top of the pul to the right of the titlel you should be able to rebase the pull request from the 1.2 legacy branch to master by clicking edit and selecting master from the drop down.

**Comment by sachaw** [comment]
@osmanovv looks like we'd be happy to merge this, but since 1.2 is about to be EOL'd, this needs to be rebased, also, the localization guide belongs in the docs: https://github.com/meshtastic/Meshtastic/tree/master/docs/developers/Firmware

**Comment by osmanovv** [comment]
@sachaw , Localization guide has been extracted to doc: https://github.com/meshtastic/Meshtastic/pull/390

New PR for v1.3 is here: https://github.com/meshtastic/Meshtastic-device/pull/1640

**Pull request closed without merging**
