### PR TITLE
fix pr #228 int float casting & made fillRect 2px smaller

### PR DESCRIPTION
**Pull request by aHVzY2g**
@mrvdb give it a try :D

### CODE REVIEW

**Comment by mrvdb** [comment]
Doesn't seem to make a difference. The brightness is set correctly, but while I press the button, the display stays off. I never see the bar.

**Comment by aHVzY2g** [comment]
But you did see the brightness bar fill up like this after your fix(#228)?

pic

**Comment by mrvdb** [comment]
No, I never saw the bar, but I assumed it was a sh1106 issue (see my note in the PR) I probably should have marked the PR 'work in progress', did not expect that to be merged right away ;-)

**Comment by aHVzY2g** [comment]
hmm okay, maybe some else with an sh1106 can confirm🤔

**Comment by geeksville** [comment]
thanks @aHVzY2g!  (yah - I shouldn't have been so quick to merge without checking on my device was LGTM)

**Comment by mrvdb** [comment]
When I introduce a delay(30) after setting the brightness I can at least see the screen.

There are more odd things though:
- it seems the sh1106 can *address* 132x64 columns in memory for display, but that doesn't necessarily mean they are visible on the OLED., so SCREEN_WIDTH is a bit ambigous. the /visible/ area is 128 wide and the library works fine by introducint the proper offsets.
- I could have sworn my other display actually displayed 132 columns, but I'm doubting myself now.

I'll make other PRs addressing the above issues. (the latter is easy, the display not showing without a delay I dont know)

**Comment by geeksville** [comment]
btw - in the  API there is a display flush operation that must be called at the end of all draw calls.  That's what actually blits the in RAM copy of the display to the OLED.  Alas, I'm AFK right now, but perhaps that is relevant (and missing in this case).

**Comment by mrvdb** [comment]
Thanks, I'll have a look

**Pull request merged**
