### PR TITLE
fix #272 add support for ttgo-lora32-v2-1-1.6 

### LINKED ISSUE #254: panic in disableInterrupt
*** Mesh service:
Guru Meditation Error: Core  1 panic'ed (Cache disabled but cached memory region accessed)
Core 1 register dump:
PC      : 0x400ec1b4  PS      : 0x00060034  A0      : 0x80081370  A1      : 0x3ffbeb90  
A2      : 0x3ffd5368  A3      : 0x00060023  A4      : 0x00060023  A5      : 0x00000001  
A6      : 0x00060023  A7      : 0x00000000  A8      : 0x800e0553  A9      : 0x00000027  
A10     : 0x0000001a  A11     : 0x00060023  A12     : 0x00060023  A13     : 0x3ffbce80  
A14     : 0x00000000  A15     : 0x00000001  SAR     : 0x0000001d  EXCCAUSE: 0x00000007  
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  
Core 1 was running in ISR context:
EPC1    : 0x40087c0d  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x400ec1b4

kevinh@kevin-server:~/development/meshtastic/meshtastic-esp32$ bin/exception_decoder.py -e .pio/build/tbeam/firmware.elf ~/tmp/ex 
stack:
0x400ec1b4: __detachInterrupt at /home/kevinh/.platformio/packages/framework-arduinoespressif32@src-dfce4f8fb340e7e3eb7d44dd50813438/cores/esp32/esp32-hal-gpio.c:282
0x4008136d: RF95Interface::disableInterrupt() at /home/kevinh/development/meshtastic/meshtastic-esp32/src/mesh/RF95Interface.cpp:41
0x40081380: RadioLibInterface::isrLevel0Common(RadioLibInterface::PendingISR) at /home/kevinh/development/meshtastic/meshtastic-esp32/src/mesh/RadioLibInterface.cpp:34
0x400813a1: RadioLibInterface::isrTxLevel0() at /home/kevinh/development/meshtastic/meshtastic-esp32/src/mesh/RadioLibInterface.cpp:53
0x400813fd: __onPinInterrupt at /home/kevinh/.platformio/packages/framework-arduinoespressif32@src-dfce4f8fb340e7e3eb7d44dd50813438/cores/esp32/esp32-hal-gpio.c:274
0x4008245d: _xt_lowint1 at /home/kevinh/development/meshtastic/esp32-arduino-lib-builder/esp-idf/components/freertos/xtensa_vectors.S:1154
0x40087c0a: spi_flash_op_block_func at /home/kevinh/development/meshtastic/esp32-arduino-lib-builder/esp-idf/components/spi_flash/cache_utils.c:201
0x40086b7b: ipc_task at /home/kevinh/development/meshtastic/esp32-arduino-lib-builder/esp-idf/components/esp32/ipc.c:62
0x40095376: vPortTaskWrapper at /home/kevinh/development/meshtastic/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)

### LINKED ISSUE #272: Brightness slider activates on TTGO-LoRa32-V2.1 with serial Puttty connection.
Anytime TTGO-LoRa32-V2.1 is connected with a serial connection with Putty or the Python API, the brightness slider activates and repeatedly  cycles from low to high. Attempting to edit the screen by pulling the GPIO0 low to ground does nothing. Ending the Putty or Python session returns the unit to normal operation.

This may not be an appropriate issue, as TTGO-LoRa32-V2 is listed as supported, but no mention of V2.1. If so, sorry , Please ignore and close.

### PR DESCRIPTION
**Pull request by aHVzY2g**
added pin defentions for ttgo-lora32-v2-1-1.6
some refrence http://www.lilygo.cn/prod_view.aspx?TypeId=50003&Id=1130&FId=t3:50003:3

### CODE REVIEW

**Comment by geeksville** [comment]
Thanks @aHVzY2g! one question and a comment.

1) Is this really a third type of lora32? (i.e. neither of the two existing types match this set of GPIOs) - I assume you checked but just confirming ;-)

2) Can you check protos/mesh.options to confirm that the string you picked for this build type is short enough to fit in hw-model?  I remember I picked a somewhat short limit and I wouldn't want to break anything? (I'm afk this morning)

**Comment by aHVzY2g** [comment]
1. Yes, but it's four versions of lora32, but I am still waiting for @thomslik to confirm for this board. 
- ttgo-lora32-v1
- ttgo-lora32-v2
- ttgo-lora32-v2-1-1.5
- ttgo-lora32-v2-1-1.6
grafik
grafik

2. I will check!

**Comment by aHVzY2g** [comment]
the limit is 16 and now I have 19, any suggestions on how to be consistent with the names and accommodate the different versions?

**Comment by geeksville** [comment]
> the limit is 16 and now I have 19, any suggestions on how to be consistent with the names and accommodate the different versions?

Hmm.  How about we change the name to "tlora-v2-1-1.6" and also change the names for the other three ttgo-lora32... to tlora...

My ulterior motive for changing the name away from "ttgo-..." is that **many** user problem reports stem from new users installing the ttgo-lora... binaries on their tbeams.  By removing "lora" from the name for these boards it will make things less ambiguous (though slightly more opaque for lora32 users ;-)).  The lora32 users will be compelled to read the README and hopefully that will lead them to also be more careful on identifying their board type.

Thoughts?

**Comment by aHVzY2g** [comment]
leaving away the ttgo sounds good to me. I will update the name for this pull and maybe update the other names in separate pull I guess. But first I will send a bin to @thomslik, to confirm it's working

**Comment by aHVzY2g** [comment]
[build.zip](https://github.com/meshtastic/Meshtastic-device/files/4918551/build.zip)
sry my bad did a copy past error

**Comment by thomslik** [comment]
Both versions appear to work and take care of that problem. But, now I can no longer toggle the screen by pulling the pin marked IO0 to ground. Is there another pin now working as IO0?

**Comment by aHVzY2g** [comment]
yes now it's pin 12

**Comment by thomslik** [comment]
Great! It works. Should one version be any better than the other?

**Comment by aHVzY2g** [comment]
no, and as I just discovered they have the same checksum :D. What I did was change the board from ttgo-lora32-v1 to ttgo-lora32-v2. But it does not make a difference at all.

I will clean up the commit's now, so it's ready to merge

**Comment by thomslik** [comment]
Thanks for all the help!

**Comment by aHVzY2g** [comment]
I am having a terrible time with squashmofing. I will close this PR cleanup everything and create a new PR

**Pull request closed without merging**
