### PR TITLE
add stm32wl5e platform and wio-e5 variant

### PR DESCRIPTION
**Pull request by majbthrd**
The STM32WL series combines a STM32 core and a SX1262 into a single chip.  There is no USB functionality in the STM32 core, so a USB serial adapter must also be included in the design (as one finds in the various ESP32 boards).

There is no Bluetooth; it would have to be a direct USB connection.  There might also be a future for this chip for REMOTE_HARDWARE_APP usage, but I haven't looked at that.

This is still a work in progress, but I wanted to commit something to keep the ball rolling.  DO NOT BUY one of these boards expecting to have a functional solution.  Also, one would need a "JTAG" (really SWD) ARM debug pod to do anything.

The biggest stumbling block is that Meshtastic uses Arduino / PlatformIO.  It is like a child's paint-with-water coloring book; as long as the invisible paint is the color that you wanted, great... but if not, tough luck.

In this case, the STM32 Arduino library doesn't support SPI comms with the SUBGHZSPI peripheral, and RadioLib uses Arduino (including SPI) as its foundation.  I've [provided a PR for STM32 Arduino](https://github.com/stm32duino/Arduino_Core_STM32/pull/1803) to make it possible, but we'll see if that gets accepted.  Moreover, even if it does get accepted, PlatformIO is already two years behind in its package of the STM32 Arduino library.

So, in this PR, in platform.ini I've commented out the build_flags that depend on this, and similarly I've commented out USE_SX1262 in ./variants/wio-e5/variant.h.  So, with the PR, it just uses the simulated radio.

Speaking of the Wio-E5 mini (formerly called LoRa-E5 mini... the LoRa trade group is cracking down on entities using its trademark in product names), I did buy a few STM32WL targets, but this one looked the most promising for Meshtastic usage (since it is basically USB-C on one side (CH340 USB-UART) and antenna on the other, and it comes with a short USB cable and a nice looking antenna).

mwio

An important gotcha with the Wio-E5 is that it is pre-programmed with their proprietary LoRa AT command firmware.  Seeedstudio make a big fuss on their web site about how they have a bootloader and how to recognize when it is operational, but then when you read further and try to make use of it yourself, you find that you have to first erase the chip (using an external debugger connected to pins that you must solder on) to unlock the firmware, and that also erases the bootloader.  Great job at wasting peoples' time, Seeedstudio. :(  So, a SWD debugger is needed.  Note that SEGGER, which is normally the gold standard of debuggers, can't unlock the chip (at least at the present J-Link version) with their normal software.  I had employ OpenOCD to make headway on that.  So, I must point out again that, presently, this is NOT for the casual user!

Another gotcha is that RadioLib wants to be able to control/poll the "DIO1" interrupt line, BUSY, and RESET  as GPIO pins.  When the peripheral is internal to the chip, that is not practical.  Moreover, there is no way to poll the SUBGHZRADIO interrupt line on the STM32WL... period.  (The interrupt is also a combination of the SX1262 interrupt *and* BUSY.)  My workaround is a bit ugly (using the RadioLib callbacks for digitalWrite and digitalRead to translate internal signals into simulated GPIO signals), but then so is the situation that forced me to write it like that.

Another gotcha is that Meshtastic makes heavy use of floating-point values, both for calculations and in debug print statements.  The STM32 Arduino PlatformIO platform appears to be using newlib without float support in sprintf, so lots of values don't appear in the debug logs.

Another gotcha is that (like you may have already found with existing PCBs used with Meshtastic) each STM32WL PCB implementation will likely have different assignments for pins for UART, RF switch controls, etc.  Thankfully Meshtastic-device has that construct already, although RadioLib can't fathom the notion of devices that use distinct PA_HI and PA_LO switch positions.  So, don't expect that  one STM32WL firmware image will work on different PCB designs.

I haven't been able to test interoperability with existing Meshtastic devices.  My experience so far with Meshtastic devices has been pretty horrible.  I bought several ESP32 off Amazon, and there seems to be no quality control.  A user might get one or two Meshtastic messages when first powering the devices up, but then it quickly gets into a funk where messages get NAKed and then later nothing seems to work.  Leave it off overnight and it briefly works again.  (For anyone about to say that I didn't have the devices far enough from each other, I tried cabling in all sort of different RF attenuators with no success.)

I think that covers everything... at least all that I can remember at the moment.

### CODE REVIEW

**Comment by thebentern** [comment]
> In this case, the STM32 Arduino library doesn't support SPI comms with the SUBGHZSPI peripheral, and RadioLib uses Arduino (including SPI) as its foundation. I've https://github.com/stm32duino/Arduino_Core_STM32/pull/1803 to make it possible, but we'll see if that gets accepted. Moreover, even if it does get accepted, PlatformIO is already two years behind in its package of the STM32 Arduino library.

Have you seen this device? https://store.rakwireless.com/products/evaluation-board-rak3172
I actually have one in my inventory because we're interested in eventually making it a Meshtastic-repeater target or as a "radio" for our linux target (portduino) which was built around using libgpiod to talk to SPI radios via a USB->SPI interface. The portduino linux issues have been a mess with all kinds of driver and kernel version issues, so we've kind of kicked the can on that one. The original radio options for those were the USB Pinedio LoRA stick and the PinePhone. 

> I haven't been able to test interoperability with existing Meshtastic devices. My experience so far with Meshtastic devices has been pretty horrible. I bought several ESP32 off Amazon, and there seems to be no quality control. A user might get one or two Meshtastic messages when first powering the devices up, but then it quickly gets into a funk where messages get NAKed and then later nothing seems to work. Leave it off overnight and it briefly works again. (For anyone about to say that I didn't have the devices far enough from each other, I tried cabling in all sort of different RF attenuators with no success.)

I highly recommend looking at the RAK Wireless targets, since they offer professional grade hardware and quality control. The devices on Amazon often seem to be QC rejects from the official stores on AliExpress or other vendors. I particularly recommend against any Heltec targets at this point since they're quite aged and have a number of quirks.

**Comment by majbthrd** [comment]
> Have you seen this device? https://store.rakwireless.com/products/evaluation-board-rak3172 I actually have one in my inventory because we're interested in eventually making it a Meshtastic-repeater target or as a "radio" for our linux target (portduino) which was built around using libgpiod to talk to SPI radios via a USB->SPI interface. The portduino linux issues have been a mess with all kinds of driver and kernel version issues, so we've kind of kicked the can on that one. The original radio options for those were the USB Pinedio LoRA stick and the PinePhone.

I had not seen it.  Thanks.  Positives seem to be that they've brought out SWD to a connector *and* (unlike the Wio-E5) BOOT0 to force the mask ROM USART bootloader.  Like the Wio-E5, you have to erase it to use it.  It also looks like you have to use a different USART from the USB one to do the firmware update.  I don't yet see documentation for the RF switch GPIO pins (utterly essential to switch the antenna between RX and 1 or 2 TX modes).

**Comment by Kongduino** [comment]
> I had not seen it. Thanks. Positives seem to be that they've brought out SWD to a connector _and_ (unlike the Wio-E5) BOOT0 to force the mask ROM USART bootloader. Like the Wio-E5, you have to erase it to use it. It also looks like you have to use a different USART from the USB one to do the firmware update. I don't yet see documentation for the RF switch GPIO pins (utterly essential to switch the antenna between RX and 1 or 2 TX modes).

A few things.

**RF switch**

```c
#define PB8                 24//NJG1801K75 RF switch (RAK3172_internal)
```

**Firmware update**

Firmware update is done via UART2 pins.
RAK3172 pinout

**Programming**

RAKwireless Unified Interface V3 (RUI3) can be used to write custom firmware for the RAK3*72 family. It comes with batteries included :-) and is compatible with Arduino IDE, Visual Studio Code, Visual Studio IDE. The bootloader and softdevice can be written to the MCU via JLink, using the 5-pin SWD connector (contrary to the RAK4631/nRF52840, you **want** to connect the RESET pin!).

RUI3 uses the Semtech sx126x library, which is the better choice in my opinion.

There's also the possibility to code for RAK3*72 with STM32Cube: there's a [howto guide](https://docs.rakwireless.com/Product-Categories/WisDuo/RAK3172-Module/Low-Level-Development/#overview), and some files to make it work for RAK3172. The user experience on STM32Cube is, well, not really enjoyable.

I have toyed with the idea of producing a Meshtastic repeater on the RAK3172, but have been too busy. I'm happy to contribute, though.

**Comment by thebentern** [comment]
@majbthrd I'll go ahead and merge this. I don't want to bury you in upstream conflicts. 
I love this conversation. I'm exited about the possibility of new extremely low power hardware. 
There's definitely some challenges ahead for shimming things some of these devices that don't have native capabilities for or platform support for some of the things that Mesthatic uses instrinsically, but I think we can get something working. With your architecture refactoring, we might even be able to to make the Mesthastic-repeater a part of the device codebase instead of a stripped down port with changes (which was our initial direction). We have some abstractions built around RadioLib that should allow us to swap out some of the interaction with the radio as needed I believe. 

> RAKwireless Unified Interface V3 (RUI3) can be used to write custom firmware for the RAK3*72 family. It comes with batteries included :-) and is compatible with Arduino IDE, Visual Studio Code, Visual Studio IDE. The bootloader and softdevice can be written to the MCU via JLink, using the 5-pin SWD connector (contrary to the RAK4631/nRF52840, you **want** to connect the RESET pin!).

I assume the RAKDAP-1 is an option here for writing bootloaders. That's been a life-saver with saving some of my abused RAK-4631 cores.

**Comment by Kongduino** [comment]
> I assume the RAKDAP-1 is an option here for writing bootloaders. That's been a life-saver with saving some of my abused RAK-4631 cores.

You would be right :-) It's why we put it on the store, hehe. I still use my bootleg JLink, but that thing has been good too. I had a BastWAN that was particularly recalcitrant, and that went away.

**Comment by GUVWAF** [comment]
@majbthrd Did you see that support for STM32WLx was just added to RadioLib?

**Pull request merged**
