### PR TITLE
Canned message plugin

### PR DESCRIPTION
**Pull request by prampec**
Plugin to feature sending predefined texts from the device without having to use the phone app.

An InputBroker is introduced, so plugins require input can be independent from the input hardware.

Screen and MeshPlugin is altered, so plugins can report screen update requests to Screen class.

### CODE REVIEW

**Comment by mc-hamster** [comment]
@prampec I see meshplugin was updated to trigger a screen change.

If that's the case, please consider doing that from within CannedMessagePlugin.cpp/h. This crosses the streams just a little bit.

**Comment by prampec** [comment]
@mc-hamster Can you please explain what "crosses the streams"?! Now Screen relies on MeshPlugin is this your concern?

(Further more, there are some lines marked with TODO-s. Please inspect those lines with care!)

**Comment by mc-hamster** [comment]
> @mc-hamster Can you please explain what "crosses the streams"?! Now Screen relies on MeshPlugin is this your concern?
> 
> (Further more, there are some lines marked with TODO-s. Please inspect those lines with care!)

Sorry for the movie reference.

Yes, why is MeshPlugin needed in screen?

**Comment by prampec** [comment]
Movie? Okay, learned something today. :)

It is all about the UIFrameEvent type. We can also do it in the other way round: define UIFrameEvent in Screen.h and reference Screen.h in MeshPlugin. What do you think?

**Comment by mc-hamster** [comment]
Got it. Thanks!

**Pull request merged**
