### PR TITLE
Split RAK-4631 targets by base board

### PR DESCRIPTION
**Pull request by thebentern**
Starting to split the RAK-4631 build targets based on pin availability / differences between the base boards

### CODE REVIEW

**Comment by thebentern** [comment]
Here are the uf2 binaries for each base board platform for testing

[rak4631_uf2.zip](https://github.com/meshtastic/Meshtastic-device/files/7673004/rak4631_uf2.zip)

**Review by garthvh — APPROVED** [review]
Looks really good, nice to have one actual variant file and multiple builds since I think there are more base boards coming in the spring.

**Comment by feh123** [comment]
Hi @thebentern thanks for this, I have a 19003 and a 5005-0 but they are not fully operational yet as I am waiting for more parts (I think my only 1910 is faulty).
I am trying the 5005 version at the moment but I get a strange effect - the OLED screen lighting adjustment line is always present and continually loops through running from zero to max (very quickly - <1 sec). This behaviour started seconds after the first install, I have tried altering a few preferences - I had is_router true and removed this, but so far nothing as stopped the looping. I don't have my 19003 hooked up to a screen yet so cannot see if the same behaviour affects that board. I am away today but I can check more tonight if you have any thoughts on the cause. Sorry to bring you problems!
@garthvh - I also notice that my 4631 is seen in the ios app but if I connect to it then the nodes page always shows no radios (yet there are two tbeams running).  And although 1910 is currently showing a gps fix the 4631 node does not appear on the map.

**Comment by thebentern** [comment]
> I am trying the 5005 version at the moment but I get a strange effect - the OLED screen lighting adjustment line is always present and continually loops through running from zero to max (very quickly - <1 sec). This behaviour started seconds after the first install, I have tried altering a few preferences - I had is_router true and removed this, but so far nothing as stopped the looping. 

I'm gonna double check this with my 5005. It sounds like there may be something squirrely with the button pin

**Comment by thebentern** [comment]
I have reproduced the bug. I think pin 5 is incorrect. I've got something to try tomorrow.

**Comment by thebentern** [comment]
@feh123 here is the updated firmware for the RAK-5005 with the correct pin mapping. Should be no funky display brightness holding bug now.
[firmware_rak_5005.zip](https://github.com/meshtastic/Meshtastic-device/files/7689668/firmware_rak_5005.zip)

**Comment by feh123** [comment]
@thebentern - the fix works well for me. Thanks!

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/meshtastic-device-1-2-49-5354c49-alpha/4502/1

**Pull request merged**
