### PR TITLE
Power Manager

### PR DESCRIPTION
**Pull request by grcasanova**
Basically trying to abstract the PMU class in order to support the boards @Corvus is actually developing. There are still a few fixes to make I may need assistance on (marked with **@todo** comments in the code) but it is pretty much the same code split in files and with proper namespaces.
Events have been placed in a separate class and, like graphics, a specific config.h file has been created to hold variables.
I may consider getting rid of those specific configs and creating a unique big file, but due to the amount of parameters I am afraid it will become an endless list of names scary enough for most users not to open.

I tried to fix the nasty warnings about AXP192_SLAVE_ADDRESS in a different way than just adding an _undef_ somewhere, now they should be gone.

Let me know your comments, it's probably going to need a deep look before merging but it is very needed as those #ifdef TBEAM Vx were really annoying.

### CODE REVIEW

**Comment by grcasanova** [comment]
_Powermanager_ namespace can be renamed _powermanagement_ or just _power_ if it is clearer

**Comment by geeksville** [comment]
looks okay to me!  Can you resolve the merge conficts and then I'll happily put it in.  I'll wait on fixing #249 until after this is merged.

**Comment by grcasanova** [comment]
do you think singletons should be under a namespace? Say `powermanager::powerFSM` vs just `powerFSM`

**Comment by grcasanova** [comment]
No idea why it fails, I can successfully compile it locally

**Comment by geeksville** [comment]
Hi @grcasanova,

The CI system will let you see the logs from its compile attempt, you can see them by clicking on "Details" above.

In this case it seems to fail on the none TBEAM based targets.  Here's the log: https://github.com/meshtastic/Meshtastic-device/pull/286/checks?check_run_id=885549756

Can you try changing to one of the failing target names? (heltec or rak815)

**Comment by grcasanova** [comment]
I think files have been changed too much to actually continue with this PR, better to close it here.

**Pull request closed without merging**
