### PR TITLE
Display status of the BT radio on screen

### PR DESCRIPTION
**Pull request by Angan7a**
Fix for: #352 - Added status of the BT radio on screen

The bluetooth status display concept:

when bluetooth is turned on and waiting for a connection, the BT symbol flashes 1 per second

when a bluetooth connection is set up, the BT symbol is showing in the top right corner

when bluetooth is off there is nothing in the top right corner.

Additionally, in the 3rd line the exact bluetooth status is displayed (for information purposes - until Wi-Fi connectivity is implemented) .

If everything is ok, then BT can be replaced with the appropriate symbol.

### CODE REVIEW

**Comment by mc-hamster** [comment]
I'll do a deep dive to figure out why this is failing either tonight or tomorrow.

**Comment by mc-hamster** [comment]
I checked out the code from your branch and was able to reproduce the problem identified in the CI build.

To reproduce it:

Open "platform.ini" and change the value for "default_envs" to "lora-relay-v1" (without quotes).

**Comment by geeksville** [comment]
yep - this is a good idea, but can you add a commit so that it will also build for the nrf52 boards (such as lora-relay-v1)?  For those boards it would be fine to just have the bluetooth status stay forever unknown (stateBT).  Someday for the NRF52 bluetooth implementation someone else could add the code to set stateBT on that platform.

**Comment by Angan7a** [comment]
Any comments are very valuable!
This week is very busy, but I hope to find some time and finish this PR :-)

**Comment by geeksville** [comment]
awesome!  sorry to make you go through these extra hoops.

**Pull request closed without merging**
