### PR TITLE
Fix for #357 - Bluetooth pairing pin disable on devices with no display

### PR DESCRIPTION
**Pull request by BeardyWalrus**
fix for #357
use the presence of ssd1306 display to set display functionality for Bluetooth security.
resolves the issue with devices with no display being unable to show Bluetooth pairing pin code

### CODE REVIEW

**Comment by BeardyWalrus** [comment]
Apologies for the messy PR, let me know if you need any changes.

**Comment by mc-hamster** [comment]
What happens when multiple devices try to pair a meshtastic node without a display? What's the user experience like?

From a security perspective, what would be the concern if a node is part of a mesh network and someone tries to pair with it?

I understand this is a work around, it there anything else we can do to harden this from people inadvertently connecting with a device?

What's going through my mind is let's say someone has a screen-less device setup in a router-only configuration. That would be located in a place where many people would have access to the device.

Maybe we only allow authentication-free ble pairing if the device has been recently started? Maybe a grace period of a few minutes?

**Comment by BeardyWalrus** [comment]
There is certainly a number of challenges with a codeless pairing. 

No pinless binding is protected from MITM attacks. 

I'm not sure how many devices have a button, which could be used to activate pinless pairing, but if you have physical access, then a screen is always going to be more secure. 

We could try setting a default passcode instead of disabling it entirely, but this is barely more secure than pinless.

As for multi bindings, I'm hesitant to restrict a new connection unless we can reliably tell that the current connection is stale, this might need a lot more testing, as I have limited access to Bluetooth devices to test. 

I did note from reading the documentation on BLE4.2 that pinless pairing supports a post binding pin verification, which would be useful to prevent MITM attacks, but this will only work on devices with displays.

**Comment by mc-hamster** [comment]
Very good points. 

Here’s a list of boards that supports this firmware:

https://www.dropbox.com/s/gly6z21qqps7uvc/espMeshtasticBoards_ev01.xls?dl=0

In main.cpp, there is:

void userButtonPressedLong()
{
    screen.adjustBrightness();
}

Maybe that can be reused for sceeenless pairing?

**Comment by BeardyWalrus** [comment]
Looks like the OneButton library supports an attachDoubleClick method. 
Feels nicer not hijacking other functionality. 
I should have time this weekend to knock this out. 

https://github.com/mathertel/OneButton

**Comment by mc-hamster** [comment]
Cool!

**Comment by BeardyWalrus** [comment]
@mc-hamster 
This got a lot more complex than I hoped.
I was having a head time resetting the security parameters after Bluetooth is initialized, so went with a default password for users with no display, and users can also override the default password with a double press of the user button. We might only want one of these, let me know and I can adjust as needed.

**Comment by mc-hamster** [comment]
It looks good. Github won't give me the option to merge it because the pull is still a draft mode.

**Comment by geeksville** [comment]
hi ya'll I'm back on the internet now and I'll reply to this great PR idea later today.  Yeah - I think changing the flow so that a press is required is a sufficient alternative to PIN (but we wouldn't want to allow PINless without at least a press)

**Comment by mc-hamster** [comment]
Removed myself and added @geeksville as a reviewer. His comment said he'll take a look at this.

**Comment by geeksville** [comment]
hi @BeardyWalrus looks great to me - sorry I forgot to check this till now!

**Comment by mc-hamster** [comment]
Woohoo! Awesome!

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/first-boot-flashing-screen-logo/2154/14

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/ble-just-works-pairing-for-screenless-devices/2273/3

**Pull request merged**
