### PR TITLE
#927 add SSL notification at boot

### LINKED ISSUE #927: When generating SSL certs, display "Please wait..." on the screen.
When generating SSL certs, display "Please wait..." on the screen or some other message/animation to indicate that the device is busy.

This happens the first reboot after wifi settings are applied on the device.

### PR DESCRIPTION
**Pull request by rxt1077**
Resolves #927 by creating a screen that says "Creating SSL Certificate, Please wait..." at boot.

### CODE REVIEW

**Comment by sachaw** [comment]
Just confirming, is this also displayed when generating an SSL cert whilst the device is on (not during boot)

**Comment by rxt1077** [comment]
Hmm... I don't think so. I didn't know that was an option. I'll have to
look at it. How would you trigger that?

**Comment by mc-hamster** [comment]
> Just confirming, is this also displayed when generating an SSL cert whilst the device is on (not during boot)

I’m not aware of other ssl generation other than the one time at boot.

**Comment by sachaw** [comment]
May be something else then, I know at-least on more recent versions of the firmware, when I set the WiFi details after being flashed the device freezes as it appears to be generating a cert (as the console states). then comes good once it's done. The traditional behavior of generating one at startup is what I used to get. I'll take a look if this commit works for me.

**Comment by rxt1077** [comment]
Thank you!

**Comment by rxt1077** [comment]
Thank you!

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/meshtastic-device-1-2-48-alpha/4359/1

**Comment by mc-hamster** [comment]
@rxt1077 Your change is now live. Thanks!

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/meshtastic-device-1-2-49-5354c49-alpha/4502/1

**Pull request merged**
