### PR TITLE
Fix GPS turned on then off immediately every 2 minutes

### PR DESCRIPTION
**Pull request by wfang2002**
## Thank you for sending in a pull request, here's some tips to get started!

Issue reported in group https://meshtastic.discourse.group/t/how-gps-works-on-meshtastic/1972/4

The problem is  lastWakeStartMsec which is assigned a more recent time (https://github.com/meshtastic/Meshtastic-device/blob/master/src/gps/GPS.cpp#L217) than the unsigned uint32 value of now, causing (now - lastWakeStartMsec) overflow in line of https://github.com/meshtastic/Meshtastic-device/blob/master/src/gps/GPS.cpp#L243.

Fixed by re-assigning now with most recent time.

### CODE REVIEW

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/how-gps-works-on-meshtastic/1972/7

**Comment by geeksville** [comment]
Thanks @wfang2002, but this change doesn't seem correct to me.  You are effectively making the check against gps_attempt_time disabled.

Why not just "meshtastic --set gps_attempt_time 99999999"? (or some other very large number of seconds)

**Comment by wfang2002** [comment]
@geeksville the real issue is the variables now and lastWakeStartMsec are both type of uint32, and now has chance of smaller than lastWakeStartMsec without the fix, causing (now - lastWakeStartMsec) overflow to 0xFFFFFFFF (4294967295).

It would be more clear if you see the debug output below:

        // We've been awake too long - force sleep
        auto wakeTime = getWakeTime();
        bool tooLong = wakeTime != UINT32_MAX && (now - lastWakeStartMsec) > wakeTime;
        if (tooLong) DEBUG_MSG("tooLong=%d, now=%u, lastWakeStartMsec=%u, (now - lastWakeStartMsec)=%u, wakeTime=%u\n", 
          tooLong, now, lastWakeStartMsec, (now - lastWakeStartMsec), wakeTime);

`22:21:02.719 > 06:21:01 [GPS] tooLong=1, now=123642, lastWakeStartMsec=123643, (now - lastWakeStartMsec)=4294967295, wakeTime=900000`

**Comment by geeksville** [comment]
@wfang2002 good point, and I was certainly being a bit sloppy about the "50 day rollover time" problem with millis() (i.e. 32 bits).  We should definitely fix that.  Are you seeing this problem occur prior to 50 days of device on time? (just so I understand the error)

**Comment by wfang2002** [comment]
@geeksville don't have to wait for 50 days, it happens every 2 minutes. In the above debug log, "now" is 123642 ms, i.e. at the 123 second after device power up.
The root cause is "lastWakeStartMsec" is assigned a value larger than "now" (123643 vs 123643).  since lastWakeStartMsec and now are both uint32, the result of  (now - lastWakeStartMsec) gets  typecast to uint32 too, which is 4294967295 instead of -1, and force the value of tooLong to always true, and so force GPS to sleep immediately, before GPS location is fixed.

**Comment by wfang2002** [comment]
BTW, to reproduce this problem you need a device supports GPS wake / sleep, i.e. PIN_GPS_WAKE is defined and actually functional.

**Comment by geeksville** [comment]
ohh!  I see what you mean!  Thanks for the help!  the problem turns out to not be rollover related at all.  it is because setAwake(true) is assigning a slightly newer version of millis() which can be a tick or two after the (stale) copy of "now".  Your fix nicely fixes now to be guaranteed to be >= that cached value.

**Pull request merged**
