### PR TITLE
Added is_always_powered preference

### PR DESCRIPTION
**Pull request by thebentern**
The sibling PR in the protobufs repo
https://github.com/meshtastic/Meshtastic-protobufs/pull/36

### CODE REVIEW

**Comment by thebentern** [comment]
Since my daily driver is windows, I also dropped a .bat equivalent of regen-protos.sh in there that works with the windows version of the binaries for the same release of the proto generation software

**Review by Solarvortx — APPROVED** [review]
ok @solanaceae

**Comment by sachaw** [comment]
I'll re-run and merge this soon.

**Comment by sachaw** [comment]
@thebentern Should be a good amount of progress with the web UI included in the build artefact (assuming it didn't screw it up).

**Comment by thebentern** [comment]
Ooh! I'll have to check it out. I haven't messed with the web project recently. I need to get back into it.

**Pull request merged**
