### PR TITLE
TTGO_T_ECHO to use batteries, PIN_EINK_PWR_ON must be set to high

### PR DESCRIPTION
**Pull request by Pedestrian11**

### CODE REVIEW

**Comment by caveman99** [comment]
This is done later on here when the EInk is initialized: https://github.com/meshtastic/Meshtastic-device/blob/f2dec07c8ddf448b5d0e3073214e2c297c5e1552/src/graphics/EInkDisplay2.cpp#L153

What is the reason to do it virtually right after we started booting?

**Comment by sachaw** [comment]
@Pedestrian11 Could you please confirm if this is needed or now.

**Comment by Pedestrian11** [comment]
PIN_EINK_PWR_ON doesn't just control e-paper.  There are other peripherals  .

**Comment by geeksville** [comment]
@pedestrian11 I agree, EINK_PWR_ON net is poorly named and controls other stuff also.  IMO this is a good fix.

**Comment by geeksville** [comment]
hmm, @andrekir reported that this didn't fix #990 for him.  And looking more at the code I agree that the existing code at the line listed by @caveman99 should be doing the same thing as this fix.  @Pedestrian11 did this change fix #990 on your board?  Thanks for the contribution btw.

**Comment by geeksville** [comment]
adding @andrekir note from the discord chat (to prevent losing it when I look later):

> just noticed something different, though the reset still behaves the same (red led blinks twice), pressing the user button afterwards causes a device reset. before this didn't happen.

**Comment by geeksville** [comment]
note from @andrekir:
> just noticed something different, though the reset still behaves the same (red led blinks twice), pressing the user button afterwards causes a device reset. before this didn't happen.

**Comment by Pedestrian11** [comment]
Thanks for your reply. One more question is after t-Echo goes to sleep.  Do you want to set IO0 to sleep wake pin?  After t-Echo sleep, press IO0 to enter DUF mode.

**Pull request merged**
