### PR TITLE
No SuperDeepSleep for RAK4631 and T-Echo

### PR DESCRIPTION
**Pull request by claesg**
Removed the SDS (SuperDeepSleep) for NRF52 boards
Added battery sense for T-Echo
I don't have a T-Echo so that part is not tested.
This PR fixes bug #827

### CODE REVIEW

**Comment by claesg** [comment]
There is a build error in the CI that i dont get when i build locally
```
src/nrf52/main-nrf52.cpp: In function 'bool loopCanSleep()':
src/nrf52/main-nrf52.cpp:23:13: error: 'tud_cdc_connected' was not declared in this scope
     return !tud_cdc_connected();
             ^~~~~~~~~~~~~~~~~
*** [.pio/build/rak4631/src/nrf52/main-nrf52.cpp.o] Error 1
========================= [FAILED] Took 39.19 seconds =========================

Environment    Status    Duration
-------------  --------  ------------
rak4631        FAILED    00:00:39.186
==================== 1 failed, 0 succeeded in 00:00:39.186 ====================
Error: Process completed with exit code 1.
```
I'll look into that later today

**Comment by claesg** [comment]
I did a 'git submodule update --force' and ran build target 'clean' and now I have it in my local build aswell.
Not sure what to do about it since this line was added 3 months ago.

**Comment by claesg** [comment]
I found that I did not get the platformio.ini part of this change
https://github.com/meshtastic/Meshtastic-device/pull/831/commits/28af18389bf5a5dcb775de7d1c350fa2bb7a4e26
I had to do a stash, pull and stash pop to get it since I had my own changes to platformio.ini
Now I can build locally again

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/serial-port-on-rak4631-gone-after-loading-dev-build/3691/6

**Comment by garthvh** [comment]
> There is a build error in the CI that i dont get when i build locally
> 
> ```
> src/nrf52/main-nrf52.cpp: In function 'bool loopCanSleep()':
> src/nrf52/main-nrf52.cpp:23:13: error: 'tud_cdc_connected' was not declared in this scope
>      return !tud_cdc_connected();
>              ^~~~~~~~~~~~~~~~~
> *** [.pio/build/rak4631/src/nrf52/main-nrf52.cpp.o] Error 1
> ========================= [FAILED] Took 39.19 seconds =========================
> 
> Environment    Status    Duration
> -------------  --------  ------------
> rak4631        FAILED    00:00:39.186
> ==================== 1 failed, 0 succeeded in 00:00:39.186 ====================
> Error: Process completed with exit code 1.
> ```
> 
> I'll look into that later today



> There is a build error in the CI that i dont get when i build locally
> 
> ```
> src/nrf52/main-nrf52.cpp: In function 'bool loopCanSleep()':
> src/nrf52/main-nrf52.cpp:23:13: error: 'tud_cdc_connected' was not declared in this scope
>      return !tud_cdc_connected();
>              ^~~~~~~~~~~~~~~~~
> *** [.pio/build/rak4631/src/nrf52/main-nrf52.cpp.o] Error 1
> ========================= [FAILED] Took 39.19 seconds =========================
> 
> Environment    Status    Duration
> -------------  --------  ------------
> rak4631        FAILED    00:00:39.186
> ==================== 1 failed, 0 succeeded in 00:00:39.186 ====================
> Error: Process completed with exit code 1.
> ```
> 
> I'll look into that later today

I am getting this error when building locally

**Comment by claesg** [comment]
Have you tried to build using 
`bin/build-all.sh`
That works and it seems to resolve things for me.
After that i have
```
Meshtastic-esp32$ grep -r tud_cdc_connected
<CUT>
grep: .pio/build/rak4631/src/nrf52/main-nrf52.cpp.o: binary file matches
grep: .pio/build/rak4631/libFrameworkArduino.a: binary file matches
grep: .pio/build/rak4631/FrameworkArduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/Adafruit_USBD_CDC.cpp.o: binary file matches
src/nrf52/main-nrf52.cpp:    return !tud_cdc_connected();
```
After that I can build in VSCode too

**Comment by geeksville** [comment]
the build is kinda busted because of some upstream code in the adafruit nrf52 (the cdc stuff moved).  I'm working on a fix but won't be done until tomorrow.

**Comment by HookdomPonix** [comment]
Good to know - I'd love to watch when you get it done to see what you did as I'm still learning this whole thing.

**Comment by HookdomPonix** [comment]
We get a good build now - but still no USB on the RAK4631.

**Comment by geeksville** [comment]
@claesg and @HookdomPonix thanks!  When you say no USB on RAK4631, can you tell me which of the following work:

* the device appears as /dev/ttyACMx (or whatever is appropriate for your OS)
* meshtastic-python can get device info with "meshtastic --info"?
* you see debug serial info on /dev/ttyACMx?

I'll get my RAK4631 out of the box tomorrow and try to replicate.

**Comment by HookdomPonix** [comment]
In my case the ttyACMX device never appears in LInux.  

It does do so fine when I smash over to the bootloader to load older code, and it works fine with the release .43 and .39 builds.  But nothing after I rock a custom build (which compiles now).   

Kernel dmesg does not indicate a device failing to be added to the system either - and dmesg for sure shows the .39 firmware presenting the device to the OS.

**Comment by geeksville** [comment]
hmm @HookdomPonix  - can you try running "pio update" - it sounds like your local machine might not have my fixes for the nordic 52 arduino goo.

**Comment by geeksville** [comment]
@HookdomPonix ooh!  I just noticed an unrelated problem.  I'll make another bug and work on that tomorrow morning.

**Comment by HookdomPonix** [comment]
That did seem to work - RAK serial is back up and working.

**Pull request merged**
