### PR TITLE
Add 1.54, 2.9 and 4.2 inch e-Paper support for RAK4361 boards - with partial updates for faster screen transitions

### PR DESCRIPTION
**Pull request by markbirss**
This PR is an further enhancement of [PR1199](https://github.com/meshtastic/Meshtastic-device/pull/1199) to add 1.54, 2.9 and 4.2 inch e-Paper support  with partial updates for faster screen transitions

Library
_____
T-ECHO - Is initialised and implemented differently and still requires
(https://github.com/meshtastic/GxEPD2)

1.54, 2.9 and 4.2 inch - uses current public GxEPD2 library 
https://github.com/ZinggJM/GxEPD2.git

The  RAK14000 2.13 inch b/w 250x122 display does not support partial updates

Purchase links 
____________
200x200
1.54 inch e-paper display high resolution 200x200 partial refresh fast speed GDEW0154M09
https://www.buy-lcd.com/products/-381

296x128
2.9 inch e-paper display SPI Support for partial refresh 4 grayscale e-ink module screen GDEW029T5D
https://www.buy-lcd.com/products/-51

300x400
 4.2 inch e-ink panel SPI interface 4 Grayscale buy e-paper display partial refresh GDEW042T2
https://www.buy-lcd.com/products/-85

Epaper HAT Connection Adapter Board for E Ink Display
https://www.buy-lcd.com/products/-27

### CODE REVIEW

**Comment by markbirss** [comment]
Kindly review and comment

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/open-hardware-board/4135/5

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/rak4631-e-ink-rak14000/4366/2

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/e-paper-display-rak/6269/6

**Pull request merged**
