### PR TITLE
misc fixes

### PR DESCRIPTION
**Pull request by geeksville**

### CODE REVIEW

**Comment by feh123** [comment]
@geeksville thanks for this - I would like to try the new master. I have a question based on ignorance of esp32 procedures. Normally I would do something like git pull origin master to get the latest version. What should I use to get these new changes?

**Comment by geeksville** [comment]
> @geeksville thanks for this - I would like to try the new master. I have a question based on ignorance of esp32 procedures. Normally I would do something like git pull origin master to get the latest version. What should I use to get these new changes?

That's almost it, but here's a fuller description: https://github.com/geeksville/Meshtastic-esp32/blob/master/docs/software/build-instructions.md

However, these changes are not yet fixing the #187 gps lock bug, I'll be fixing that today.

**Comment by feh123** [comment]
@geeksville thanks for the link. I have downloaded and set up platformio. In step 3 I downloaded the master on github but I could not get step 4 to run. Do I have to somehow install the downloaded file using the platformio terminal? I did look at platformio.ini - do I just remove the # from HW_VERSION and then add EU835 to the line after HW_VERSION? Should EU835 be EU865?
Apologies for these questions - I tried to figure out what to do but no success.

**Comment by geeksville** [comment]
oops sorry- I hadn't noticed those instructions had gotten a little stale.  I'll update them today.

Better instructions ;-)

In your shell:

export COUNTRY=EU865
pio run --environment tbeam -t upload

This will build and upload a tbeam load.

I should push out an 'official' build with these changes today or tomorrow.

**Comment by feh123** [comment]
@geeksville that's great. Thanks.

**Comment by feh123** [comment]
@geeksville I followed the instructions and successfully installed the latest clone from today. I will leave my other tbeams on 0.7.8 beta and see what changes I find. Thanks. I am still on the app - 0.7.80 and currently although the tbeam says its connected to the phone (from serial putty) the app says please pair but does not in fact pair. I sent in a bug report. I still find that my phone BT settings menu does not immediately try to connect when a hit a tbeam icon. If I press the icon for my other paired devices it immediately tries to connect.

**Pull request merged**
