### PR TITLE
setting newline characters to be \r\n instead of \n to make serial te…

### PR DESCRIPTION
**Pull request by gregwalters**
…rminal clients happy

Running a command like `screen /dev/ttyUSB0 921600` results in lines not wrapping properly. Instead there's just one long continuous line of debug out put that wraps when it hits the end of the terminal.

### CODE REVIEW

**Comment by gregwalters** [comment]
I should probably flash this to ensure it actually works as expected. Still working on getting a build environment setup.

**Comment by gregwalters** [comment]
Built the modified firmware and can confirm that `screen /dev/ttyUSB0 921600` shows _better_ but not perfect output:

```
fix type 3
processUBX: counter hit MAX_PAYLOAD_SIZE
fix type 3
Transition powerFSM transition=Screen-on timeout, from=ON to=DARK
                                                                 Turning off screen
fix type 3
fix type 3
pressing
Trigger powerFSM 1
                  Transition powerFSM transition=Press, from=DARK to=ON
                                                                       Sending network ping to 0xff, with position=0, wantReplies=1
sending owner !2462abf83f20/Unknown 3f20/?20
Update DB node 0x20, rx_time=0
old user !2462abf83f20/Unknown 3f20/?20
updating changed=0 user !2462abf83f20/Unknown 3f20/?20
Adding broadcast record for fr=0x20,to=0xff,id=30
Sending packet via interface fr=0x20,to=0xff,id=30
immediate send on mesh fr=0x20,to=0xff,id=30
 (txGood=1,rxGood=0,rxBad=0)
Turning on screen
fix type 3
Completed sending to=0xff, id=30
pressing
Trigger powerFSM 1
                  Transition powerFSM transition=Press, from=ON to=ON
                                                                     Setting fast framerate
Setting idle framerate
fix type 3
processUBX: counter hit MAX_PAYLOAD_SIZE
```

Not sure where those debugging messages are generated but suspect that they're internal to the powerFSM code and I don't wanna muck with it.

**Comment by geeksville** [comment]
Thank you for this pull-request.  It is very kind and I love pull requests.  I've been using the standard platformio console tool to develop and never even noticed that carriage returns were not being generated.

Alas though I don't think I can take this PR.  

All of the debug printing is via the SerialConsole "console" instance.  So no need to change all those strings to include \r.  Instead I think we should just add a small override in SerialConsole.h something like:

```
virtual size_t write(uint8_t c) { 
  if(c == '\n') // prefix any newlines with carriage return
    RedirectablePrint::write('\r');
  RedirectablePrint::write(c);
 }
```

This would allow keeping the 'standard' Cish behavior of \n is all you need as a line terminator and it would fix all possible usages.

Do you want to make a change like this or should I?  Sorry I didn't notice the missing carriage returns before.  I'd love to take other PRs from you ;-).

**Comment by geeksville** [comment]
Hi Greg, I hope this isn't annoying to you.  I know you put in work ;-).  But I just applied the change based on what you noticed.

**Pull request closed without merging**
