### PR TITLE
MCP9808 sensor implementation

### PR DESCRIPTION
**Pull request by RicInNewMexico**
Added support for the MCP9808 temperature sensor from Adafruit. 

Changes passed CI build on my repo, ci-build firmware flashed to T-Beam v1.1 and verified working.

### CODE REVIEW

**Comment by mc-hamster** [comment]
Approved to run CI actions.

Code review is good.

Before I approve, just curious -- what is firmware size before and after this change?

**Comment by RicInNewMexico** [comment]
> 

Prior: 1723728
After: 1726160

And not sure why your ci-build failed, the "build everything" was successful, it looks like it may be due to changes in #1186 to the ci-build action.

**Comment by thebentern** [comment]
I'm looking into the ci-build failure. It's definitely something with the new PR artifacts build. That's a brand new addition so apparently it still has a kind or two in it.

**Comment by mc-hamster** [comment]
> Prior: 1723728 After: 1726160
> 
> And not sure why your ci-build failed, the "build everything" was successful, it looks like it may be due to changes in #1186 to the ci-build action.
> 
> Edited to add: Just re-ran my CI build on my repo (in-sync with all commits to meshtastic-device) just to verify. Results: https://github.com/RicInNewMexico/Meshtastic-device/actions/runs/1800367368

About 2.5k. Thanks!

**Comment by thebentern** [comment]
> > I'm looking into the ci-build failure. It's definitely something with the new PR artifacts build. That's a brand new addition so apparently it still has a kind or two in it.
> 
> Are we ok merging this as is or do you want to use this to test the ci?

I want to test my CI change. Apparently the Github action context for forks is different than branches within the current repo. Github added a pull_request_target event that you can utilize instead that is supposed to dispatch it as if it originated from the target repo supposedly, so I'm hoping my change resolves this. Otherwise, we'll have to remove the new PR artifact comment step from the ci-build..

**Comment by RicInNewMexico** [comment]
> > > I'm looking into the ci-build failure. It's definitely something with the new PR artifacts build. That's a brand new addition so apparently it still has a kind or two in it.
> > 
> > 
> > Are we ok merging this as is or do you want to use this to test the ci?
> 
> I want to test my CI change. Apparently the Github action context for forks is different than branches within the current repo. Github added a pull_request_target event that you can utilize instead that is supposed to dispatch it as if it originated from the target repo supposedly, so I'm hoping my change resolves this. Otherwise, we'll have to remove the new PR artifact comment step from the ci-build..

Yay! Success!

**Comment by thebentern** [comment]
Awesome! Great work on the new sensor support.

**Pull request merged**
