### PR TITLE
Adjust year, hour, minute for PCF8563

### PR DESCRIPTION
**Pull request by rjmcdougall**
The PCF8563 has a mod(100) year format, and months/days which start at zero.

This request updates perhapsSetRTC() and readFromRTC() accordingly.

### CODE REVIEW

**Comment by caveman99** [comment]
Thanks you for your contribution, let me move that file to the right spot :-)

**Comment by andrekir** [comment]
```
23:13:12 56 [GPS] NMEA GPS time 2022-09-28 18:49:52
23:13:12 56 [GPS] Upgrading time to RTC 1664390992 secs (quality 0)
18:49:52 56 [GPS] PCF8563_RTC setDateTime 2022-09-28 18:49:52 1664390992
18:49:52 56 [GPS] Read RTC time from PCF8563 as 1060431148
```
looks like setting RTC from GPS time is failing, and stale RTC time is used.

**Comment by rjmcdougall** [comment]
That's odd -- I did do a similar check on my device. Let me test again and
see -- but yes the output there looks like it did not stick.

**Comment by rjmcdougall** [comment]
> ```
> 23:13:12 56 [GPS] NMEA GPS time 2022-09-28 18:49:52
> 23:13:12 56 [GPS] Upgrading time to RTC 1664390992 secs (quality 0)
> 18:49:52 56 [GPS] PCF8563_RTC setDateTime 2022-09-28 18:49:52 1664390992
> 18:49:52 56 [GPS] Read RTC time from PCF8563 as 1060431148
> ```
> 
> looks like setting RTC from GPS time is failing, and stale RTC time is used.


Hi -- I'm hoping to resolve this. May I ask is your comment confirming the bug & fix, or are you still seeing the same issue?

I sync'ed and build this branch and tested again on my techo's and see the correct behavior:

23:31:45 49 [GPS] NMEA GPS time 2022-10-03 23:31:45
23:31:45 49 [GPS] Upgrading time to RTC 1664839905 secs (quality 0)
23:31:45 49 [GPS] PCF8563_RTC setDateTime 2022-10-03 23:31:45 1664839905
23:31:45 49 [GPS] Read RTC time from PCF8563 as 1664839905
23:31:45 49 [GPS] publishing pos@0:2, hasVal=0, GPSlock=0
23:31:45 49 [GPS] onGPSChanged() pos@0, time=1664839905, lat=0, lon=0, alt=0
23:31:45 49 [GPS] updatePosition LOCAL pos@0, time=1664839905, latI=0, lonI=0, alt=0
23:31:45 49 [GPS] Node status update: 1 online, 1 total

**Comment by andrekir** [comment]
@rjmcdougall just flashed firmware-1.3.42.2faf507 and still seeing the same behavior:

```
01:13:17 58 [GPS] NMEA GPS time 2022-10-04 00:45:32
01:13:17 58 [GPS] Upgrading time to RTC 1664844332 secs (quality 0)
00:45:32 58 [GPS] PCF8563_RTC setDateTime 2022-10-04 00:45:32 1664844332
00:45:32 58 [GPS] Read RTC time from PCF8563 as 1018080748
08:12:28 58 [GPS] publishing pos@0:2, hasVal=0, GPSlock=0
08:12:28 58 [GPS] onGPSChanged() pos@0, time=1018080748, lat=0, lon=0, alt=0
```

looks like [`rtc.setDateTime`](https://github.com/meshtastic/Meshtastic-device/blob/2faf507c0de6ada2a2c98c8c4c891078bdc84c2f/src/gps/RTC.cpp#L115) isn't taking.

**Comment by rjmcdougall** [comment]
I can't reproduce what you are showing above. WHen I flash this build to
techo I get:


   -

   ??:??:?? 8 Read RTC time from PCF8563 as 1664839403
   -

   23:23:23 8 Using MSL altitude model
   -

   23:24:15 60 [GPS] NMEA GPS time 2022-10-03 23:24:17
   -

   23:24:15 60 [GPS] Upgrading time to RTC 1664839457 secs (quality 0)
   -

   23:24:17 60 [GPS] PCF8563_RTC setDateTime 2022-10-03 23:24:17 1664839457
   -

   23:24:17 60 [GPS] Read RTC time from PCF8563 as 1664839457
   -

   23:24:17 60 [GPS] publishing ***@***.***:2, hasVal=0, GPSlock=0
   -

   23:24:17 60 [GPS] onGPSChanged() ***@***.***, time=1664839457, lat=0, lon=0,
   alt=0
   -

   23:24:17 61 [GPS] updatePosition LOCAL ***@***.***, time=1664839457, latI=0,
   lonI=0, alt=0

**Comment by caveman99** [comment]
this issue and the fix is a red herring, there's a bug in the underlying library. The function calls actually use 4 digit years but computate the registers of the chip wrong. See https://github.com/lewisxhe/PCF8563_Library/issues/2

I'm gonna compile a version with the library fix for testing.

**Comment by caveman99** [comment]
i made a test firmware with the patch included in the lib. Please try https://github.com/meshtastic/Meshtastic-device/suites/8601265102/artifacts/385620384

**Comment by andrekir** [comment]
fixed. thank you all!

```
??:??:?? 1 Meshtastic hwvendor=7, swver=1.3.42.b148781-d
(...)
11:43:21 59 [GPS] NMEA GPS time 2022-10-04 11:43:22
11:43:21 59 [GPS] Upgrading time to RTC 1664883802 secs (quality 0)
11:43:22 59 [GPS] PCF8563_RTC setDateTime 2022-10-04 11:43:22 1664883802
11:43:22 59 [GPS] Read RTC time from PCF8563 as 1664883802
```

**Pull request merged**
