### PR TITLE
Changes to Environmental Measurement App

### PR DESCRIPTION
**Pull request by crossan007**
Adds a custom UI Frame to display environment details.

image

https://user-images.githubusercontent.com/11679900/108791075-3a3d6b00-754c-11eb-99ae-75954dc4d6b8.mp4

Plugins may be allocated their own frame by overriding in their header:
```
 virtual bool wantUIFrame() { return true; }
 ```

When this is defined, the UI will call the plugin's `drawFrame(OLEDDisplay *display, OLEDDisplayUiState *state, int16_t x, int16_t y);` method

Known bugs:
Receiving a text message will drop you to the 0th UI Frame; which used to be the text message frame, but is now the environment frame

### CODE REVIEW

**Comment by crossan007** [comment]
@geeksville @mc-hamster I'd be curious to see what you think of the direction I've gone with allowing plugins access to create a UI frame.

If it's something you support, I have additional ideas to further develop this.

I'm also open to breaking out the UI thing into a separate PR, since there _are_ fixes to the environmental plugin here as well

**Comment by geeksville** [comment]
I like the plugin UI frame idea (and it would be great to eventually use this to move the text message drawing into the text message plugin and out of screen.cpp).  And eventually I'd like to refactor these plugin enhancements (see also ProtobufPlugin) to not be single inheritance but more of a 'mixin' pattern.

**Comment by crossan007** [comment]
This MR now has a dependency on https://github.com/meshtastic/esp8266-oled-ssd1306/pull/2

**Comment by mc-hamster** [comment]
Thanks @crossan007

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/temperature-sensing/2668/4

**Pull request merged**
