### PR TITLE
Converted status text to graphical header, Issue#134

### PR DESCRIPTION
**Pull request by Professr**
This is built on top of the branch I sent a PR for (#196), since I needed the percentage for drawing the battery graphic.  It'll merge fine, just hope it doesn't cause confusion

### CODE REVIEW

**Comment by geeksville** [comment]
ooh sounds awesome.  I can't wait to try it tomorrow.

**Comment by geeksville** [comment]
btw - if you think you'll be continuing to play with/extend this project do you want me to add you to the org?  Also I can try to be more rigorous about my own PRs so that someone other than me (i.e. you) has at least a chance to scan them over before they go in (no pressure though)

**Comment by Professr** [comment]
This is only my 2nd full day with the code, but I like it so far.  I do tend to stay active with things that have a hardware component, and this combines three of my favorite concepts (handheld DIY, mesh, and secure communications) so I'll probably be pestering this codebase for a while if you'll have me :P  You know the code far better than I do, so I'm not sure how useful it'd be for me to look things over by default.  If you'd like an extra pair of eyes on something, I'm always happy to try.  If we stick to making an issue for each thing we're working on, we should be able to keep it all merge-safe.  I tend to make a lot of little tweaks here and there on my own projects, but I'm trying to keep it as structured as I can here (I'm just new to github processes and only used to the basics of local git repos).

**Comment by geeksville** [comment]
Ok that sounds fine.  I'll add you, but no pressure.  I'm just generally in
favor of having a second set of eyes scanning commits when possible.  If
you see a PR from me and something doesn't look right - feel free to stick
in a comment on github and I won't take offense.

**Comment by Professr** [comment]
Cool!  I agree in principle, definitely, and will try to keep up with and look at what I can.

**Comment by geeksville** [comment]
ooh - looks great - much more polished than before!  I also like the idea of the pound prefix for the channel name.

**Pull request merged**
