### PR TITLE
Make Observer to be able to observe multiple Observables.

### PR DESCRIPTION
**Pull request by prampec**
I was not sure why observers can only observe one observable. So I have changed that.

### CODE REVIEW

**Comment by prampec** [comment]
With this change an Observable can have more Observers, and with that it is possible to an Observer to observe multiple event sources.
This is required for e.g. InputBroker an observe multiple inputs, when let's say a device is equipped with two rotary encoders.

**Comment by sachaw** [comment]
@prampec Was this change ever needed or will we gain anything from merging? Thanks.

**Comment by prampec** [comment]
"This is required for e.g. InputBroker an observe multiple inputs, when let's say a device is equipped with two rotary encoders."
InputBroker listens to inputs, but currently we can only have one. If we want to have both a keypad and a rotary encoder and some hardware buttons, we need to listen to multiple inputs.

(Not sure what is failing tho.)

**Comment by caveman99** [comment]
The native test runs fine from my commandline, no core dump. Must be something CI specific

**Comment by sachaw** [comment]
Great work @prampec

**Pull request merged**
