### PR TITLE
Re-init config_state after we switch to nodeinfo

### PR DESCRIPTION
**Pull request by thebentern**
Initial config sending was only being sent on a freshly booted / reset device. This will resolve that hopefully

### CODE REVIEW

**Comment by caveman99** [comment]
good catch!

**Comment by caveman99** [comment]
i still wonder if there's a way to iterate over that localconfig enum. Other than counting to 6.

**Comment by garthvh** [comment]
It would be easier for me to parse if it had the has things like hasGps on myInfo.  config.hasLoRa for example

**Comment by caveman99** [comment]
can you provide an example? because the Localconfig on C++ has a 'is populated' bool for every branch. See https://github.com/meshtastic/Meshtastic-device/blob/7a50ab4de2f7e720dc39dede4c284b1423321743/src/mesh/NodeDB.cpp#L435-L466

**Comment by garthvh** [comment]
I now have payload variant and some other populated details so I got it working.

**Pull request merged**
