### PR TITLE
Change GPS Pin on Heltec v2.1

### PR DESCRIPTION
**Pull request by ssysm**
Looks like battery pin on the heltec v2.1 board conflict with the existing GPS pins definition. Swapped them to another pair of unused pins.

### CODE REVIEW

**Comment by caveman99** [comment]
Good Catch. 37 would not have worked for TX anyway since this is an input-only pin. GPI without O so to speak :-) 
In situations where GPIO are tight we only need the RX pin for NMEA operation anyway, TX is only used for bidirectional chips like ublox.

**Comment by ssysm** [comment]
Tested using Neo-6M GPS module. GPS reading correctly.

**Comment by mc-hamster** [comment]
Thanks!

**Comment by caveman99** [comment]
This was kinda not merged !? Just closed.

**Pull request merged**
