### PR TITLE
Correction for wrong battery display on tlora_v2_1_16 board

### PR DESCRIPTION
**Pull request by costonisp**
Added a ADC_MULTIPLIER for tlora_v2_1_16 board
 the display was showing 3.81V and 60% for a full battery, which measured 4.18V

after adding #define ADC_MULTIPLIER 2.2  the display was within 1% accurate.

### CODE REVIEW

**Comment by costonisp** [comment]
the platformio.ini was not meant to be uploaded, just the variant.h

**Comment by thebentern** [comment]
Great first contribution! Glad we could get a fix for this one in. Thanks!

**Comment by mc-hamster** [comment]
Thanks!

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/heltec-v2-1-fw-1-2-53-not-going-into-sleep-mode/4974/1

**Pull request merged**
