### PR TITLE
Fix for #632 (move web server to osthread) and #611 (move airtime to osthread)

### PR DESCRIPTION
**Pull request by mc-hamster**
## Thank you for sending in a pull request, here's some tips to get started!

(Please delete all these tips and replace with your text)

- Before starting on some new big chunk of code, it it is optional but highly recommended to open an issue first
  to say "hey, I think this idea X should be implemented and I'm starting work on it. My general plan is Y, any feedback
  is appreciated." This will allow other devs to potentially save you time by not accidentially duplicating work etc...
- Please do not check in files that don't have real changes
- Please do not reformat lines that you didn't have to change the code on
- We recommend using the [Visual Studio Code](https://platformio.org/install/ide?install=vscode) editor,
  because automatically follows our indentation rules and it's auto reformatting will not cause spurious changes to lines.
- If your PR fixes a bug, mention "fixes #bugnum" somewhere in your pull request description.
- If your other co-developers have comments on your PR please tweak as needed.

### CODE REVIEW

**Comment by geeksville** [comment]
hey @mc-hamster I noticed this CI problem.  Something I didn't think of, we either need to move the http stuff to its own directory (not mesh/wifi, how about mesh/http) or we need to add nasty ifdefs to exclude it for the linux build.  (Because we don't have the http server running on linux and possibly won't ever)

If it is mesh/http we can have platformio.ini not try to build that directory when targeting linux.

Do you want to make that change or I can do it?

**Comment by mc-hamster** [comment]
> hey @mc-hamster I noticed this CI problem. Something I didn't think of, we either need to move the http stuff to its own directory (not mesh/wifi, how about mesh/http) or we need to add nasty ifdefs to exclude it for the linux build. (Because we don't have the http server running on linux and possibly won't ever)
> 
> If it is mesh/http we can have platformio.ini not try to build that directory when targeting linux.
> 
> Do you want to make that change or I can do it?

Please go ahead. I’m unable to reproduce this locally so it’s taking a whole lot more time to address than I would like. 

Thanks!

**Comment by geeksville** [comment]
pr sent!

**Comment by mc-hamster** [comment]
@geeksville Worked like a charm! Thanks!

**Pull request merged**
