### PR TITLE
Add RAK4361_5005_RAK14000 board variant and enable e-Paper module

### PR DESCRIPTION
**Pull request by markbirss**
Add new board variant

RAK 4361 5005-O base with RAK14000 e-Paper module 2.13 inch 250x122 b/w DEPG0213BNS800F41HP

RAK4361_5005_RAK14000

At first i could not get the screen to fit, fixed but now have a line down bottom of screen that i cannot seem to fix

The author of GxEPD2 wont do specific support for this e-Paper
https://forum.arduino.cc/t/good-dispay-epaper-for-arduino/419657/536

So we are stuck with using the WaveShare 213_B74 support that is similar

### CODE REVIEW

**Comment by markbirss** [comment]
Kindly review and comment

**Comment by thebentern** [comment]
image
I hesitate to add another target for the RAK devices, but I'm guessing the HAS_EINK is what's tripping us up here? Does that cause an exception when it can't find the display? If not and we can still use the OLED with normal operation, I'd say merge it into the normal 5005 variant defs.

**Comment by markbirss** [comment]
@thebentern, 

Yes HAS_EINK and SPI_INTERFACE_COUNT=2 would cause lora radio init to fail when e-Paper was not found

**Comment by thebentern** [comment]
Mark, I want to go ahead and merge this but I think we need to tweak a couple of small things.

1. I think we should rename the variant to RAK4361_5005_EINK, so that it doesn't further confuse the already confusing string of RAK wireless board numbers for the variant. 
2. We changed the CI build recently to use a job matrix for parallel target building. So your new target will need to be added to this collection for that to work: https://github.com/meshtastic/Meshtastic-device/blob/54f062e94d26b222fca3e3b0478e42eda03ddba2/.github/workflows/main_matrix.yml#L162

**Review by markbirss — COMMENTED** [review]
@thebentern 

Ok i have renamed it to rak4631_5005_eink

Kindly review the changes

**Review by markbirss — COMMENTED** [review]
Just pointed to https://github.com/meshtastic/GxEPD2

**Comment by markbirss** [comment]
@thebentern 

I cannot edit main_matrix.yml yet

**Comment by markbirss** [comment]
@thebentern

can you kindly update the CI workflow

[Meshtastic-device/.github/workflows/main_matrix.yml](https://github.com/meshtastic/Meshtastic-device/blob/54f062e94d26b222fca3e3b0478e42eda03ddba2/.github/workflows/main_matrix.yml#L162)

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/rak4631-e-ink-rak14000/4366/2

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/e-paper-display-rak/6269/6

**Pull request merged**
