### PR TITLE
Bluetooth mode unification and behavior tweaks

### PR DESCRIPTION
**Pull request by thebentern**
Okay folks, this mushroomed into a much bigger set of changes than I initially intended, but sometimes one thing leads to another...

I think I have all 3 of our new modes of bluetooth working across nrf and esp32 devices: RandomPin, FixedPin, and NoPin (just-works).

Due to security concerns and consistency among the platforms, we have a new default pairing mode. If your device boots up for the first time (or with with a stale device state), we make an initial decision to secure by default using fixed pin (123456 unless config.bluetooth.fixed_pin is set to otherwise) if your device has no detected display. If the device does have a detected display, then we default to the traditional random pin. Either way, we display the pin if a screen is present now.
The NoPin (just works) mode which was formerly the default of the nrf52 platform is now no longer the default on that platform and is optional on esp32 as well.

I also fixed some bugs and tweaked some things: 

- First time pairing on RAK-4631 now should send want_config response instead of only doing so on subsequent connects.

- Setting configs like lora and bluetooth that require reboot will automatically trigger a reboot 5 seconds after setting them. A new rebooting screen will appear so that this doesn't appear to be a crash to the end user.

- We now show the device bluetooth name in the boot screen for better user experience per #1634, thanks @mc-hamster.

Please test

### CODE REVIEW

**Comment by thebentern** [comment]
Closes #1634

**Comment by garthvh** [comment]
Closes #1435

**Comment by thebentern** [comment]
Here is my suggested testing setup:

### Desktop
- Download latest firmware ([Pull request artifacts](https://github.com/meshtastic/Meshtastic-device/pull/1636#issuecomment-1218212447)) zip file is up to date with the latest successful build.
- Flash firmware using the device install scripts (device-install.sh and device-install.bat).
- Start `meshtastic --noproto` or other serial monitor to log things if anything out of the ordinary occurs during testing. Provide the logs on any issue reports if possible.

### Phone
- Ensure the latest mobile app is installed on phone(s) for testing. (For now only test iOS, please. We're working on figuring out the issues on Android)
- Forget the pairing for the device on the phone(s).

### Device 
- Ensure all devices on the mesh are also on the same firmware version. This prevents issues from occuring due to protobuf differences or mesh behavior changes.
- Try starting with one device at first to test pairing and single device behavior. Then introduce another or even more to simulate a larger mesh.

## Reporting issues:
- Report issue as a comment to this PR or on the #meshtastic-1_3 channel on Discord
- Provide a detailed description of the issue encountered and expected behavior
- Please reference all clients and versions in the testing setup in the issue report
- Please reference all device hardware and versions (if different from latest) in the issue report

- Provide serial logs or screenshots in the issue report if available
- Full versions are important for ruling out previously solved issues 

@andrekir we've noticed some initial bluetooth pairing issues on the Android app with this firmware version that did not occur in 1.3.38. I'm not convinced that these are a part of the minimal transport changes implemented. The breaking protobuf changes might between the two _might_ the issue. Could we get a new version of the Android app released with regenerated protobufs to confirm or rule that out?

**Comment by andrekir** [comment]
@thebentern I bumped protos, debug apk from the CI build [here](https://github.com/meshtastic/Meshtastic-Android/suites/7918988865/artifacts/337359204). I was not able to test.

**Comment by thebentern** [comment]
Thanks @andrekir! We'll check it out

**Pull request merged**
