### PR TITLE
Enable RAK14000 2.13 inch b/w E-Ink partial update support

### PR DESCRIPTION
**Pull request by markbirss**
Changed from GxEPD2_213_B74 (which was not going to give partial update support on this display) to GxEPD2_213_BN - RAK14000 2.13 inch b/w 250x122

### CODE REVIEW

**Comment by markbirss** [comment]
Kindly review and comment

**Comment by caveman99** [comment]
Looks good to me, i'll flash and test once CI is done...

**Comment by caveman99** [comment]
it works good, shame the line in the bottom is still there!

**Comment by markbirss** [comment]
> it works good, shame the line in the bottom is still there!

Ah yes, the issue i think is because the library support has resolution 250x128 but E-ink is only 250x122, the 128 chosen so it dividable by 8

But if you change the lines to 128 the dots at the bottom dont fit on screen...

It is this only screen having this issue at the moment of the ones i have

**Pull request merged**
