### PR TITLE
Threading refactored

### PR DESCRIPTION
**Pull request by grcasanova**
Code refactoring for Threading, compiles. Got rid of useless includes, a cyclic dependency regarding Periodic* stuff and millis defined via FreeRTOS to ease off _Arduino.h_ being everywhere.
Functional namespaces, may expand _timing.h/.cpp_ in the future to include more time-related cross-platform functions if needed.
Lastly, _.gitignore_ edited for Mac users.

### CODE REVIEW

**Comment by geeksville** [comment]
Looks great @grcasanova, can you update the branch so that it is up-to-date wrt master so it can merge?

**Comment by grcasanova** [comment]
pull from master and merge changes?

**Comment by geeksville** [comment]
yes - It has conficts that have to be resolved before it can merge.

**Comment by grcasanova** [comment]
done

**Comment by geeksville** [comment]
cool beans!

**Pull request merged**
