### PR TITLE
Backport T-Echo fix for GPS and Reset Button to 1.2

### PR DESCRIPTION
**Pull request by caveman99**

### CODE REVIEW

**Comment by Vertikar** [comment]
May have hit a bug on my tbeams, at least one of them is now saying no GPS module after updating to 1.2.64
I'll raise an issue when I have a chance to investigate

**Comment by Vertikar** [comment]
Looks like its gone away after a second reboot.

**Comment by runestone74** [comment]
Sorry to say, still having problem with GPS way off. First two from the phone, and the last from the T-Echo GPS
IMG_2723

**Comment by thebentern** [comment]
@runestone74, you might troubleshoot this by trying a factory reset

**Pull request merged**
