### PR TITLE
Implement listen-before-talk mechanism

### PR DESCRIPTION
**Pull request by GUVWAF**
As discussed in #firmware on Discord, we need a real listen-before-talk mechanism. Previously, the device already set a random delay before it starts transmitting in order to let others reconfigure their radio, to avoid collisions and implement timing-based routing priority. 
On top of that, if after this delay we were set to transmit or receive (checked by _canSendImmediately_()), we need to restart another random delay for the same reasons. Furthermore, if the channel is busy right at the point where we want to transmit (checked by _isChannelActive_()), we also start this random delay. 

Tested this with the latest release on two T-beams, seems to work.

### CODE REVIEW

**Comment by mc-hamster** [comment]
@GUVWAF Awesome PR. I've added one comment for change, very minor.

**Comment by tim292stro** [comment]
No objections, but questions for the pull author: What's the power impact of just continuing to listen to the channel versus the randomized wait time?
  
A lot of the party-bus style protocols (even serial over copper) have a multi-step window for:
1. Ack window, defined keep-out period after the transmitter's packet (or last packet in a burst) where an Ack is expected (less than two packet times for start, and short payload)
2. Subsequent packet from same sender in same transmission (shortest gap duration, gets a multi-packet transmission over with ASAP)
3. Other transmitter sending first packet in new transmission (medium gap duration, lets other nodes get a word in edgewise)
4. Retransmit attempt from (longest gap duration, keeps a loud node getting NAKs or no response at all from saturating the air-time - also give a transmitter a chance to process a multi-packet NAK to figure out which packets to retransmit without holding up the channel)
  
Working like this, if you have a busy channel - any receiver waiting to transmit can be smart about its wait time.  For a single packet, the next transmitter just needs to wait for the ack to finish, then seize the channel with a _very_ short randomized interval listening all the way until the interval timer has expired.  If it's a multi-packet transmission, looking at a well-formed header's packet count "n of x", a more defined wait time can be determined to not even use the power listening until around the end of transmission is heard.  Then a _very_ short randomized delay again for the period after the ACK/NAK window.
  
RSSI channel busy detection after missing a header or with a different protocol than what is programmed for that occupies the same frequency, the LoRa radio can still use the random interval method - but starting that random timer after RSSI drops off should lead to higher channel utilization and throughput.
  
Some metrics on how busy the channel is and how many ACK vs NAKs for channel quality would be good to have as well - and rolling in some behavioral channel renegotiation might be useful for jamming resistance as a potential feature add down the road perhaps - but that's a drift from the Pull Request's intention..

**Comment by mc-hamster** [comment]
> No objections, but questions for the pull author: What's the power impact of just continuing to listen to the channel versus the randomized wait time?
> 
> A lot of the party-bus style protocols (even serial over copper) have a multi-step window for:
> 
> 1. Ack window, defined keep-out period after the transmitter's packet (or last packet in a burst) where an Ack is expected (less than two packet times for start, and short payload)
> 2. Subsequent packet from same sender in same transmission (shortest gap duration, gets a multi-packet transmission over with ASAP)
> 3. Other transmitter sending first packet in new transmission (medium gap duration, lets other nodes get a word in edgewise)
> 4. Retransmit attempt from (longest gap duration, keeps a loud node getting NAKs or no response at all from saturating the air-time - also give a transmitter a chance to process a multi-packet NAK to figure out which packets to retransmit without holding up the channel)
> 
> Working like this, if you have a busy channel - any receiver waiting to transmit can be smart about its wait time. For a single packet, the next transmitter just needs to wait for the ack to finish, then seize the channel with a _very_ short randomized interval listening all the way until the interval timer has expired. If it's a multi-packet transmission, looking at a well-formed header's packet count "n of x", a more defined wait time can be determined to not even use the power listening until around the end of transmission is heard. Then a _very_ short randomized delay again for the period after the ACK/NAK window.
> 
> RSSI channel busy detection after missing a header or with a different protocol than what is programmed for that occupies the same frequency, the LoRa radio can still use the random interval method - but starting that random timer after RSSI drops off should lead to higher channel utilization and throughput.
> 
> Some metrics on how busy the channel is and how many ACK vs NAKs for channel quality would be good to have as well - and rolling in some behavioral channel renegotiation might be useful for jamming resistance as a potential feature add down the road perhaps - but that's a drift from the Pull Request's intention..

Picking a random interval is industry standard and used in similar broadcast protocols. Eg: 

- https://en.wikipedia.org/wiki/Carrier-sense_multiple_access_with_collision_detection

**Comment by tim292stro** [comment]
> Picking a random interval is industry standard and used in similar broadcast protocols. Eg:
> 
> * https://en.wikipedia.org/wiki/Carrier-sense_multiple_access_with_collision_detection

Agreed, but note I'm proposing roughly the mechanism outlined in CSMA - it should have a random interval after the quiet time starts to promote air-time fairness - not just waiting a random interval at the first detection of RSSI.  The shorter interval for the "next packet" means that you will have short-term unfairness so that a large message can get through all at once, and the longer interval for retries means that a link with low quality has fairness built into the protocol.  Having the window in the middle between "next packet" and "retry" improves the fairness for other transmitters - and that is the window you'd want to have randomized, and listening right up to the interval timeout to see if someone else won.
  
CSMA in the wiki article is interchanging the word "packet" (in our LoRa context) with "frame" (in the article's ethernet context).  I know I'm late to the party on this pull, but also to my shame I haven't yet had a moment to dig into the Meshtastic low level protocol - and I'm not aware if in-network traffic is differentiated from non-network RSSI in the collision detection scheme (the crux of what I'm babbling about here).
  
I bought a bunch of TTGO t-beams to dig into and play with this but they haven't arrived yet.

**Comment by JmCasler** [comment]
> I bought a bunch of TTGO t-beams to dig into and play with this but they haven't arrived yet.

We always welcome improvement. Let's get this PR in and if it can be improved, then it can be improved. No need to wait for perfect :) 

Happy to have you on board!

**Comment by GUVWAF** [comment]
> No objections, but questions for the pull author: What's the power impact of just continuing to listen to the channel versus the randomized wait time?

I agree that it would actually be better to continuously listen to the channel until it is free, then start the random delay. My PR definitely is not perfect, but it is at least a lot safer than having no listen-before-talk at all. 
In fact, I already started working on a discrete-event simulator (based on [this repo](https://github.com/lucagioacchini/lora-network-simulator)) to simulate channel access, as well as the scalability of the routing protocol. I will let you know when it is in a more mature state :) 

> I know I'm late to the party on this pull, but also to my shame I haven't yet had a moment to dig into the Meshtastic low level protocol - and I'm not aware if in-network traffic is differentiated from non-network RSSI in the collision detection scheme (the crux of what I'm babbling about here).

The new function _isChannelActive_() calls the _scanChannel_() function of the radio chip, which checks for a LoRa preamble, so in-network traffic.

**Comment by GUVWAF** [comment]
> @GUVWAF Awesome PR. I've added one comment for change, very minor.

@mc-hamster Where did you add this comment? I cannot seem to find it.

**Comment by mc-hamster** [comment]
> > @GUVWAF Awesome PR. I've added one comment for change, very minor.
> 
> @mc-hamster Where did you add this comment? I cannot seem to find it.

Catch :) 

image

**Review by mc-hamster — APPROVED** [review]
Awesome!

**Comment by mc-hamster** [comment]
Thanks for the PR!

**Comment by thebentern** [comment]
Awesome first contribution, @GUVWAF! Thanks

**Comment by mc-hamster** [comment]
> Awesome first contribution, @GUVWAF! Thanks

This was his first?!?! No way, this was pro style!

@GUVWAF !!!!!!!

**Comment by GUVWAF** [comment]
@thebentern @mc-hamster Thanks, indeed it was my first. Happy to help, I enjoy thinking about optimizing these lower layers, as well as the routing algorithm.

**Comment by tim292stro** [comment]
> ...I enjoy thinking about optimizing these lower layers, as well as the routing algorithm...

@GUVWAF count me in - I had more time to dig into the lower layer protocol this past week and your work is a terrific start.  I have some ideas...  Day job and family means I only get to allocate about 4-10 hours a week on projects (and I have soooo many), but Meshtastic is getting more of my attention as of late.  Of course my nodes arrived last night so I have enough to try some off-channel air-time congestion and higher hop counts - have about 20 to play with now.

**Pull request merged**
