### PR TITLE
Combine WIFI state into an enum

### LINKED ISSUE #1601: Combine WIFI state into an enum
as suggested by @Noki
"wifi.mode (`off`,`client`,`ap`,`ap_hidden`)"
would be more concise.

### PR DESCRIPTION
**Pull request by sachaw**
Closes #1601, #1595

### CODE REVIEW

**Comment by sachaw** [comment]
Currently no provisioning for `Config_WiFiConfig_WiFiMode_Disabled`

**Comment by garthvh** [comment]
Enabled is not part of an enum anywhere else are we going to make this change to all 6 modules with enabled? They does not match our other config at all. Has anyone mocked up a UI with this structure, seems confusing.

**Comment by garthvh** [comment]
Enabled as a drop down does not make sense to me in the UI

**Comment by sachaw** [comment]
It could easily work as a boolean enabled field and an enum for the rest. I agree, that this would be more inline with the convention used by the modules.

**Comment by garthvh** [comment]
Perfect, the modes make sense as an enum, but we have the enabled in 7 other places :)

**Comment by thebentern** [comment]
I dig it!

**Review by thebentern — APPROVED** [review]

**Comment by garthvh** [comment]
Merging so I can create a release for device and iOS

**Pull request merged**
